extensions:
    pimgento-csv-family-export-show:
        module: pim/form/common/edit-form

    pimgento-csv-family-export-show-tabs:
        module: pim/form/common/form-tabs
        parent: pimgento-csv-family-export-show
        targetZone: content
        position: 100

    pimgento-csv-family-export-show-properties:
        module: pim/job/common/edit/properties
        parent: pimgento-csv-family-export-show-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    pimgento-csv-family-export-show-history:
        module: pim/common/tab/history
        parent: pimgento-csv-family-export-show-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    pimgento-csv-family-export-show-properties-code:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-show-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pimgento-csv-family-export-show-properties-label:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-show-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    pimgento-csv-family-export-show-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-show-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    pimgento-csv-family-export-show-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-show-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    pimgento-csv-family-export-show-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-show-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    pimgento-csv-family-export-show-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: pimgento-csv-family-export-show-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_header.help

    pimgento-csv-family-export-show-properties-activated-locales-list:
        module: activated-locales-list
        parent: pimgento-csv-family-export-show-properties
        position: 155
        targetZone: global-settings
        config:
            fieldCode: configuration.labelLocale
            readOnly: true
            label: pim_enhanced_connector.family_processor.locale.label
            tooltip: pim_enhanced_connector.family_processor.locale.help

    pimgento-csv-family-export-show-label:
        module: pim/job/common/edit/label
        parent: pimgento-csv-family-export-show
        targetZone: title
        position: 100

    pimgento-csv-family-export-show-meta:
        module: pim/job/common/edit/meta
        parent: pimgento-csv-family-export-show
        targetZone: meta
        position: 100

    pimgento-csv-family-export-show-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pimgento-csv-family-export-show
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pimgento-csv-family-export-show-edit:
        module: pim/common/redirect
        parent: pimgento-csv-family-export-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            identifier:
                path: code
                name: code

    pimgento-csv-family-export-show-launch:
        module: pim/job/common/edit/launch
        parent: pimgento-csv-family-export-show
        targetZone: buttons
        position: 110
        config:
            label: pim_enrich.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_export_launch
            identifier:
                path: code
                name: code
