extensions:
    pimgento-csv-family-export-edit:
        module: pim/form/common/edit-form

    pimgento-csv-family-export-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: pimgento-csv-family-export-edit
        position: 1000

    pimgento-csv-family-export-edit-tabs:
        module: pim/form/common/form-tabs
        parent: pimgento-csv-family-export-edit
        targetZone: content
        position: 100

    pimgento-csv-family-export-edit-properties:
        module: pim/job/common/edit/properties
        parent: pimgento-csv-family-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    pimgento-csv-family-export-edit-history:
        module: pim/common/tab/history
        parent: pimgento-csv-family-export-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    pimgento-csv-family-export-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pimgento-csv-family-export-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    pimgento-csv-family-export-edit-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-edit-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    pimgento-csv-family-export-edit-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-edit-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    pimgento-csv-family-export-edit-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: pimgento-csv-family-export-edit-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    pimgento-csv-family-export-edit-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: pimgento-csv-family-export-edit-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_header.help

    pimgento-csv-family-export-edit-properties-activated-locales-list:
        module: activated-locales-list
        parent: pimgento-csv-family-export-edit-properties
        position: 155
        targetZone: global-settings
        config:
            fieldCode: configuration.labelLocale
            readOnly: false
            label: pim_enhanced_connector.family_processor.locale.label
            tooltip: pim_enhanced_connector.family_processor.locale.help

    pimgento-csv-family-export-edit-label:
        module: pim/job/common/edit/label
        parent: pimgento-csv-family-export-edit
        targetZone: title
        position: 100

    pimgento-csv-family-export-edit-meta:
        module: pim/job/common/edit/meta
        parent: pimgento-csv-family-export-edit
        targetZone: meta
        position: 100

    pimgento-csv-family-export-edit-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pimgento-csv-family-export-edit
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pimgento-csv-family-export-edit-delete:
        module: pim/job/export/edit/delete
        parent: pimgento-csv-family-export-edit
        targetZone: buttons
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    pimgento-csv-family-export-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: pimgento-csv-family-export-edit
        targetZone: buttons
        position: 120

    pimgento-csv-family-export-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: pimgento-csv-family-export-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    pimgento-csv-family-export-edit-state:
        module: pim/form/common/state
        parent: pimgento-csv-family-export-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    pimgento-csv-family-export-edit-validation:
        module: pim/job/common/edit/validation
        parent: pimgento-csv-family-export-edit
